name: build-discord-bot
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2

      - name: 'Set up latest JDK N from jdk.java.net'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17

      - name: 'Grant execute permission for gradlew'
        working-directory: ./discord-bot
        run: chmod +x gradlew

      - name: 'Build with Gradle'
        working-directory: ./discord-bot
        run: ./gradlew build
